# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(856, 673)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exit_bt = QtWidgets.QPushButton(self.centralwidget)
        self.exit_bt.setGeometry(QtCore.QRect(670, 20, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.exit_bt.setFont(font)
        self.exit_bt.setStyleSheet("")
        self.exit_bt.setObjectName("exit_bt")
        self.add_question = QtWidgets.QPushButton(self.centralwidget)
        self.add_question.setGeometry(QtCore.QRect(480, 20, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.add_question.setFont(font)
        self.add_question.setStyleSheet("")
        self.add_question.setObjectName("add_question")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 200, 761, 321))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.rbtn1 = QtWidgets.QRadioButton(self.groupBox)
        self.rbtn1.setGeometry(QtCore.QRect(130, 80, 191, 71))
        self.rbtn1.setObjectName("rbtn1")
        self.rbtn2 = QtWidgets.QRadioButton(self.groupBox)
        self.rbtn2.setGeometry(QtCore.QRect(460, 90, 151, 61))
        self.rbtn2.setObjectName("rbtn2")
        self.rbtn3 = QtWidgets.QRadioButton(self.groupBox)
        self.rbtn3.setGeometry(QtCore.QRect(130, 210, 151, 71))
        self.rbtn3.setObjectName("rbtn3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_4.setGeometry(QtCore.QRect(460, 220, 201, 51))
        self.radioButton_4.setObjectName("radioButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 130, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.answer_bt = QtWidgets.QPushButton(self.centralwidget)
        self.answer_bt.setGeometry(QtCore.QRect(300, 550, 211, 51))
        self.answer_bt.setObjectName("answer_bt")
        self.groupBox.raise_()
        self.exit_bt.raise_()
        self.add_question.raise_()
        self.label.raise_()
        self.answer_bt.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 856, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exit_bt.setText(_translate("MainWindow", "Exit"))
        self.add_question.setText(_translate("MainWindow", "Add question"))
        self.groupBox.setTitle(_translate("MainWindow", "Answer"))
        self.rbtn1.setText(_translate("MainWindow", "Answ1"))
        self.rbtn2.setText(_translate("MainWindow", "Answ2"))
        self.rbtn3.setText(_translate("MainWindow", "Answ3"))
        self.radioButton_4.setText(_translate("MainWindow", "Answ4"))
        self.label.setText(_translate("MainWindow", "Translate text"))
        self.answer_bt.setText(_translate("MainWindow", "Go answer"))
