# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(850, 575)
        self.t_word = QtWidgets.QLineEdit(Dialog)
        self.t_word.setGeometry(QtCore.QRect(30, 90, 501, 41))
        self.t_word.setObjectName("t_word")
        self.f_word2 = QtWidgets.QLineEdit(Dialog)
        self.f_word2.setGeometry(QtCore.QRect(30, 220, 501, 41))
        self.f_word2.setObjectName("f_word2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 280, 501, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.f_word1 = QtWidgets.QLineEdit(Dialog)
        self.f_word1.setGeometry(QtCore.QRect(30, 150, 501, 41))
        self.f_word1.setObjectName("f_word1")
        self.translate = QtWidgets.QLineEdit(Dialog)
        self.translate.setGeometry(QtCore.QRect(30, 40, 501, 41))
        self.translate.setObjectName("translate")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(140, 360, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(632, 27, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.t_word.setPlaceholderText(_translate("Dialog", "Введіть правильну  відповідь..."))
        self.f_word2.setPlaceholderText(_translate("Dialog", "Введіть не правильний варіант 2..."))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "Введіть не правильний варіант 3..."))
        self.f_word1.setPlaceholderText(_translate("Dialog", "Введіть не правильний варіант 1..."))
        self.translate.setPlaceholderText(_translate("Dialog", "Введіть переклад слова..."))
        self.pushButton.setText(_translate("Dialog", "Add question"))
        self.pushButton_2.setText(_translate("Dialog", "Go home"))
